// Dutiva — Jurisdiction data layer
// Master statutory reference data for all five core Canadian jurisdictions.
// Each object is passed as `j` into every template function.
// Add new jurisdictions here; template files need no changes.

"use strict";

const JURISDICTIONS = {

  // ══════════════════════════════════════════════════════════════════════════
  // ONTARIO
  // ══════════════════════════════════════════════════════════════════════════
  ON: {
    code: "ON",
    nameEN: "Ontario",
    nameFR: "Ontario",
    // Core employment statute
    statuteEN:         "Employment Standards Act, 2000",
    statuteFR:         "Loi de 2000 sur les normes d'emploi",
    statuteCiteEN:     "S.O. 2000, c. 41",
    statuteCiteFR:     "L.O. 2000, chap. 41",
    shortEN:           "ESA",
    shortFR:           "LNE",
    // Termination notice (ESA ss. 54–57)
    termStatEN:        "ESA ss. 54–57",
    termStatFR:        "LNE arts. 54–57",
    noticeFormulaEN:   "1 week per completed year of service (max 8 weeks)",
    noticeFormulaFR:   "1 semaine par année de service accomplie (max 8 semaines)",
    probationMonths:   3,   // ESA s. 54(1)(b)
    // Severance (ESA s. 64 — only if 5+ yrs AND $2.5M payroll)
    hasSeverance:      true,
    severanceStat:     "ESA s. 64",
    severanceFormEN:   "1 week per completed year of service (max 26 weeks), where employer payroll ≥ $2.5M and employee has 5+ years",
    severanceFormFR:   "1 semaine par année de service accomplie (max 26 semaines), si la masse salariale ≥ 2,5 M$ et l'employé a 5 ans ou plus de service",
    // Wages on termination
    finalPayStat:      "ESA s. 11",
    finalPayEN:        "no later than the employee's next regular pay date",
    finalPayFR:        "au plus tard à la prochaine date de paie régulière de l'employé",
    // Vacation
    vacMinWeeks:       2,
    vacMinPct:         "4%",
    vacEnhancedEN:     "3 weeks / 6% after 5 years of service (ESA s. 35.2)",
    vacEnhancedFR:     "3 semaines / 6 % après 5 ans de service (LNE art. 35.2)",
    vacStatEN:         "ESA ss. 33–42",
    vacStatFR:         "LNE arts. 33–42",
    // Overtime
    overtimeHours:     44,
    overtimeNoteEN:    "Overtime is payable at 1.5× for hours worked beyond 44 per week (ESA s. 22).",
    overtimeNoteFR:    "Les heures supplémentaires sont payées à 1,5 fois le taux ordinaire au-delà de 44 heures par semaine (LNE art. 22).",
    // Sick leave
    paidSickDays:      0,
    sickLeaveEN:       "3 unpaid sick leave days per year (ESA s. 50.0.1); employer policies often exceed this.",
    sickLeaveFR:       "3 jours de congé de maladie non payés par année (LNE art. 50.0.1); les politiques patronales dépassent souvent ce minimum.",
    // Group termination (ESA s. 58)
    groupTermStatEN:   "ESA s. 58; O.Reg. 288/01 (Form 1 required for 50+ employees)",
    groupTermStatFR:   "LNE art. 58; Règl. de l'Ont. 288/01 (formulaire 1 requis pour 50 employés ou plus)",
    groupThreshold50:  8,   // weeks notice for 50–199 employees
    groupThreshold200: 12,
    groupThreshold500: 16,
    groupTrigger:      "50 or more employees terminated in a 4-week period",
    groupTriggerFR:    "50 employés ou plus mis à pied dans une période de 4 semaines",
    // Special Ontario-only provisions
    rightToDisconnect: true,
    rtdStatEN:         "ESA s. 21.1.2 (employers with 25+ employees must have a written policy)",
    rtdStatFR:         "LNE art. 21.1.2 (les employeurs de 25 salariés ou plus doivent avoir une politique écrite)",
    electronicMon:     true,
    emStatEN:          "ESA s. 41.1.1 (employers with 25+ employees must have a written electronic monitoring policy)",
    emStatFR:          "LNE art. 41.1.1 (les employeurs de 25 salariés ou plus doivent avoir une politique de surveillance électronique écrite)",
    nonCompeteBan:     true,
    ncStatEN:          "ESA s. 67.2 (non-compete agreements entered into after October 25, 2021, are void — executives and sale-of-business transactions are exempt)",
    ncStatFR:          "LNE art. 67.2 (les accords de non-concurrence conclus après le 25 octobre 2021 sont nuls — les cadres supérieurs et les transactions de vente d'entreprise sont exemptés)",
    // Harassment
    harassStatEN:      "Occupational Health and Safety Act, R.S.O. 1990, c. O.1, ss. 32.0.1–32.0.8",
    harassStatFR:      "Loi sur la santé et la sécurité au travail, L.R.O. 1990, chap. O.1, arts. 32.0.1–32.0.8",
    harassBodyEN:      "Ministry of Labour, Immigration, Training and Skills Development (MLITSD)",
    harassBodyFR:      "Ministère du Travail, de l'Immigration, de la Formation et du Développement des compétences (MTIFDC)",
    harassFineEN:      "$100,000 per offence (corporation); $50,000 (individual)",
    harassFineFR:      "100 000 $ par infraction (société); 50 000 $ (particulier)",
    // Privacy
    privacyStatEN:     "PIPEDA (federal baseline); Ontario has no private-sector privacy statute — federal PIPEDA fills the gap",
    privacyStatFR:     "LPRPDE (norme fédérale); l'Ontario n'a pas de loi provinciale sur la protection des renseignements personnels dans le secteur privé",
    // Human rights
    hrStatEN:          "Human Rights Code, R.S.O. 1990, c. H.19",
    hrStatFR:          "Code des droits de la personne, L.R.O. 1990, chap. H.19",
    // Pay equity
    payEquityEN:       "Pay Equity Act, R.S.O. 1990, c. P.7 — mandatory for employers with 10+ employees; job-to-job and proportional methods",
    payEquityFR:       "Loi sur l'équité salariale, L.R.O. 1990, chap. P.7 — obligatoire pour les employeurs de 10 salariés ou plus",
    // Governing law
    govLawEN:          "Province of Ontario",
    govLawFR:          "province de l'Ontario",
    // Wrong-dismissal recourse
    unjustDismissEN:   "ESA s. 96 (complaint to Employment Standards Officer); common law wrongful dismissal action in Superior Court",
    unjustDismissFR:   "LNE art. 96 (plainte à l'Agent des normes d'emploi); action en common law devant la Cour supérieure",
    // Parental leave
    parentalStatEN:    "ESA ss. 46–49.1 (pregnancy leave: up to 17 weeks; parental leave: up to 61 weeks)",
    parentalStatFR:    "LNE arts. 46–49.1 (congé de maternité : jusqu'à 17 semaines; congé parental : jusqu'à 61 semaines)",
    // ROE
    roeStatEN:         "Employment Insurance Regulations, SOR/96-332, s. 19(3) — ROE Code E (termination without just cause); Code N (resignation)",
    roeStatFR:         "Règlement sur l'assurance-emploi, DORS/96-332, art. 19(3) — Code de RE E (congédiement sans motif valable); Code N (démission)",
    // Waksdale flag (relevant for all ON termination documents)
    waksdaleApplies:   true,
    waksdaleNoteEN:    "Waksdale v. Swegon North America Inc., 2020 ONCA 391 — if the for-cause clause is overbroad, the entire termination section is void.",
    waksdaleNoteFR:    "Waksdale c. Swegon North America Inc., 2020 ONCA 391 — si la clause pour motif valable est trop large, toute la section de cessation est nulle.",
    dufaultNoteEN:     "Dufault v. The Corporation of the Township of Ignace, 2024 ONSC 1029 — 'active employment' language in without-cause clause voided the termination provision.",
    dufaultNoteFR:     "Dufault c. Corporation of the Township of Ignace, 2024 ONSC 1029 — le libellé d'« emploi actif » dans la clause sans motif a annulé la clause de cessation.",
    // Civil code flag
    isCivilLaw:        false,
  },

  // ══════════════════════════════════════════════════════════════════════════
  // QUÉBEC
  // ══════════════════════════════════════════════════════════════════════════
  QC: {
    code: "QC",
    nameEN: "Québec",
    nameFR: "Québec",
    statuteEN:         "Act Respecting Labour Standards",
    statuteFR:         "Loi sur les normes du travail",
    statuteCiteEN:     "CQLR c N-1.1",
    statuteCiteFR:     "RLRQ c N-1.1",
    shortEN:           "ARLS",
    shortFR:           "LNT",
    termStatEN:        "ARLS art. 82",
    termStatFR:        "LNT art. 82",
    noticeFormulaEN:   "1 week per year of service for 1–2 years; 2 weeks per year for 3+ years (ARLS art. 82)",
    noticeFormulaFR:   "1 semaine par année de service pour 1–2 ans; 2 semaines par année pour 3 ans ou plus (LNT art. 82)",
    probationMonths:   3,
    hasSeverance:      false,
    severanceStat:     "ARLS art. 82 (indemnité en remplacement du délai-congé)",
    severanceFormEN:   "No separate severance entitlement — ARLS art. 82 notice/indemnity is the primary remedy; see also art. 124 (wrongful dismissal recourse for 2+ years service)",
    severanceFormFR:   "Aucune indemnité de départ distincte — l'article 82 de la LNT (préavis ou indemnité compensatrice) est le recours principal; voir aussi l'art. 124 (recours en congédiement injustifié après 2 ans de service)",
    finalPayStat:      "ARLS art. 82.1",
    finalPayEN:        "within 72 hours of the date of termination (ARLS art. 82.1)",
    finalPayFR:        "dans les 72 heures suivant la date de cessation d'emploi (LNT art. 82.1)",
    vacMinWeeks:       2,
    vacMinPct:         "4%",
    vacEnhancedEN:     "3 weeks / 6% after 3 years of service (ARLS art. 68)",
    vacEnhancedFR:     "3 semaines / 6 % après 3 ans de service (LNT art. 68)",
    vacStatEN:         "ARLS arts. 66–77",
    vacStatFR:         "LNT arts. 66–77",
    overtimeHours:     40,
    overtimeNoteEN:    "Overtime is payable at 1.5× for hours worked beyond 40 per week (ARLS art. 55). Québec also has a right to refuse overtime in certain family-status situations (ARLS art. 59.0.1).",
    overtimeNoteFR:    "Les heures supplémentaires sont payées à 1,5 fois le taux ordinaire au-delà de 40 heures par semaine (LNT art. 55). Le Québec reconnaît également un droit de refus des heures supplémentaires dans certaines situations de statut familial (LNT art. 59.0.1).",
    paidSickDays:      2,
    sickLeaveEN:       "2 paid sick/personal leave days per year, plus up to 24 unpaid hours (ARLS art. 79.1); employer plans typically exceed this.",
    sickLeaveFR:       "2 jours de congé de maladie ou personnel payés par année, plus jusqu'à 24 heures non payées (LNT art. 79.1); les régimes patronaux dépassent généralement ce minimum.",
    groupTermStatEN:   "ARLS arts. 84.0.1–84.0.13 (10+ employees in 2 months); comité de reclassement mandatory for 50+",
    groupTermStatFR:   "LNT arts. 84.0.1–84.0.13 (10 employés ou plus dans 2 mois); comité de reclassement obligatoire pour 50 employés ou plus",
    groupThreshold50:  8,
    groupThreshold200: 12,
    groupThreshold500: 16,
    groupTrigger:      "10 or more employees terminated in a 2-month period",
    groupTriggerFR:    "10 employés ou plus mis à pied dans une période de 2 mois",
    rightToDisconnect: false,
    rtdStatEN:         null,
    rtdStatFR:         null,
    electronicMon:     false,
    emStatEN:          null,
    emStatFR:          null,
    nonCompeteBan:     false,
    ncStatEN:          "Civil Code of Québec, art. 2089 — non-competes must be in writing, limited in duration, territory and activity, and the burden of proof that the restriction goes no further than necessary lies on the employer",
    ncStatFR:          "Code civil du Québec, art. 2089 — les clauses de non-concurrence doivent être écrites, limitées quant à la durée, au territoire et à l'activité, et l'employeur a le fardeau de prouver que la restriction n'excède pas ce qui est nécessaire",
    harassStatEN:      "ARLS arts. 81.18–81.20 (psychological harassment); CNESST complaint window: 2 years",
    harassStatFR:      "LNT arts. 81.18–81.20 (harcèlement psychologique); délai de plainte à la CNESST : 2 ans",
    harassBodyEN:      "Commission des normes, de l'équité, de la santé et de la sécurité du travail (CNESST)",
    harassBodyFR:      "Commission des normes, de l'équité, de la santé et de la sécurité du travail (CNESST)",
    harassFineEN:      "Administrative penalties under ARLS art. 140; CNESST may order reinstatement, back pay and moral damages",
    harassFineFR:      "Sanctions administratives en vertu de la LNT art. 140; la CNESST peut ordonner la réintégration, les salaires rétroactifs et les dommages moraux",
    privacyStatEN:     "Act respecting the protection of personal information in the private sector (CQLR c P-39.1), as amended by Law 25 (S.Q. 2021, c. 25) — Privacy Impact Assessments required for new technology-driven data processing",
    privacyStatFR:     "Loi sur la protection des renseignements personnels dans le secteur privé (RLRQ c P-39.1), telle que modifiée par la Loi 25 (L.Q. 2021, c. 25) — des évaluations des facteurs relatifs à la vie privée sont requises pour tout nouveau traitement de données par des technologies",
    hrStatEN:          "Charter of Human Rights and Freedoms, CQLR c C-12 (quasi-constitutional; applies to private parties)",
    hrStatFR:          "Charte des droits et libertés de la personne, RLRQ c C-12 (quasi-constitutionnelle; s'applique aux parties privées)",
    payEquityEN:       "Act respecting pay equity (Loi sur l'équité salariale), CQLR c E-12.001 — mandatory for employers with 10+ employees; pay equity assessment every 5 years; CNESST enforces",
    payEquityFR:       "Loi sur l'équité salariale, RLRQ c E-12.001 — obligatoire pour les employeurs de 10 salariés ou plus; évaluation tous les 5 ans; CNESST applique",
    govLawEN:          "Province of Québec",
    govLawFR:          "province de Québec",
    unjustDismissEN:   "ARLS art. 124 (wrongful dismissal complaint after 2 years continuous service — Commission des relations du travail); Civil Code arts. 2091–2092 (insufficient notice)",
    unjustDismissFR:   "LNT art. 124 (plainte en congédiement injustifié après 2 ans de service continu — Tribunal administratif du travail); CCQ arts. 2091–2092 (préavis insuffisant)",
    parentalStatEN:    "ARLS arts. 81.4–81.17 + Régime québécois d'assurance parentale (RQAP) — more generous parental benefits than federal EI; up to 52 weeks combined (standard) or 69 weeks (extended)",
    parentalStatFR:    "LNT arts. 81.4–81.17 + Régime québécois d'assurance parentale (RQAP) — prestations parentales plus généreuses que l'AE fédérale; jusqu'à 52 semaines combinées (régime de base) ou 69 semaines (régime particulier)",
    roeStatEN:         "Service Canada ROE Web — Code E (termination); Code N (resignation); note RQAP administers parental benefits separately from EI",
    roeStatFR:         "ROE Web de Service Canada — Code E (cessation); Code N (démission); noter que le RQAP administre les prestations parentales séparément de l'AE",
    waksdaleApplies:   true,  // Québec courts have applied analogous reasoning
    waksdaleNoteEN:    "Waksdale v. Swegon North America Inc., 2020 ONCA 391 is an Ontario decision; Québec courts apply Civil Code art. 2092 (absolute right to reasonable notice) and the principle that contractual terms which derogate from minimum standards are without effect (ARLS art. 93). A termination clause that purports to limit notice below the ARLS or Civil Code minimum is void.",
    waksdaleNoteFR:    "L'arrêt Waksdale c. Swegon North America Inc., 2020 ONCA 391 est une décision ontarienne; les tribunaux québécois appliquent l'art. 2092 du CCQ (droit absolu à un délai raisonnable) et le principe selon lequel les clauses contractuelles dérogeant aux normes minimales sont sans effet (LNT art. 93). Une clause de cessation visant à limiter l'avis en deçà du minimum légal est nulle.",
    dufaultNoteEN:     "No direct Québec equivalent to Dufault, 2024 ONSC 1029 — but art. 2092 CCQ provides that any stipulation by which the employee renounces their right to obtain an indemnity for failure to give reasonable notice is null.",
    dufaultNoteFR:     "Aucun équivalent québécois direct à l'affaire Dufault 2024 ONSC 1029 — mais l'art. 2092 CCQ prévoit que toute stipulation par laquelle l'employé renonce à obtenir une indemnité pour défaut de délai-congé raisonnable est nulle.",
    isCivilLaw:        true,
    civilLawStatEN:    "Civil Code of Québec, arts. 2085–2097 (employment contract regime)",
    civilLawStatFR:    "Code civil du Québec, arts. 2085–2097 (régime du contrat de travail)",
    // Québec-specific
    languageObligEN:   "Charter of the French Language (Charte de la langue française), CQLR c C-11, s. 41, as amended by Act to Amend the Charter of the French Language (Bill 96), S.Q. 2022, c. 14 — employment agreements must be provided in French; the employee may request an English version but French prevails",
    languageObligFR:   "Charte de la langue française, RLRQ c C-11, art. 41, telle que modifiée par la Loi modifiant la Charte de la langue française (Loi 96), L.Q. 2022, c. 14 — les contrats de travail doivent être rédigés en français; l'employé peut demander une version anglaise, mais la version française prévaut",
    rqapNoteEN:        "Québec employees pay into the Régime québécois d'assurance parentale (RQAP) instead of federal EI parental benefits; RQAP is administered by the Conseil de gestion de l'assurance parentale",
    rqapNoteFR:        "Les employés québécois cotisent au Régime québécois d'assurance parentale (RQAP) plutôt qu'à l'AE fédérale pour les prestations parentales; le RQAP est administré par le Conseil de gestion de l'assurance parentale",
  },

  // ══════════════════════════════════════════════════════════════════════════
  // BRITISH COLUMBIA
  // ══════════════════════════════════════════════════════════════════════════
  BC: {
    code: "BC",
    nameEN: "British Columbia",
    nameFR: "Colombie-Britannique",
    statuteEN:         "Employment Standards Act",
    statuteFR:         "Employment Standards Act (Colombie-Britannique)",
    statuteCiteEN:     "R.S.B.C. 1996, c. 113",
    statuteCiteFR:     "R.S.B.C. 1996, ch. 113",
    shortEN:           "BC ESA",
    shortFR:           "ESA C.-B.",
    termStatEN:        "BC ESA ss. 63–64",
    termStatFR:        "ESA C.-B. arts. 63–64",
    noticeFormulaEN:   "1 week per year of service after 3 months, max 8 weeks (BC ESA s. 63)",
    noticeFormulaFR:   "1 semaine par année de service après 3 mois, max 8 semaines (ESA C.-B. art. 63)",
    probationMonths:   3,
    hasSeverance:      false,
    severanceStat:     "BC ESA — no separate severance provision; notice only",
    severanceFormEN:   "No statutory severance (separate from notice) in BC — unlike Ontario ESA s. 64 or CLC s. 235. Employers must provide notice or pay in lieu under BC ESA s. 63.",
    severanceFormFR:   "Aucune indemnité de départ distincte (séparée du préavis) en C.-B. — contrairement à la LNE de l'Ontario art. 64 ou au CCT art. 235. Les employeurs doivent accorder un préavis ou une indemnité en tenant lieu en vertu de l'ESA C.-B. art. 63.",
    finalPayStat:      "BC ESA s. 18",
    finalPayEN:        "within 48 hours of termination (BC ESA s. 18(1)); if employee resigns with notice, within 6 days of last day",
    finalPayFR:        "dans les 48 heures suivant la cessation d'emploi (ESA C.-B. art. 18(1)); si l'employé démissionne avec préavis, dans les 6 jours suivant le dernier jour de travail",
    vacMinWeeks:       2,
    vacMinPct:         "4%",
    vacEnhancedEN:     "3 weeks / 6% after 5 years of continuous service (BC ESA s. 58(2))",
    vacEnhancedFR:     "3 semaines / 6 % après 5 ans de service continu (ESA C.-B. art. 58(2))",
    vacStatEN:         "BC ESA ss. 57–61",
    vacStatFR:         "ESA C.-B. arts. 57–61",
    overtimeHours:     40,
    overtimeNoteEN:    "BC has BOTH daily overtime (1.5× after 8h; 2× after 12h) and weekly overtime (1.5× after 40h) — BC ESA ss. 35–36. This dual trigger is unique among Canadian provinces.",
    overtimeNoteFR:    "La C.-B. prévoit À LA FOIS des heures supplémentaires quotidiennes (1,5× après 8h; 2× après 12h) et hebdomadaires (1,5× après 40h) — ESA C.-B. arts. 35–36. Ce double déclencheur est unique parmi les provinces canadiennes.",
    paidSickDays:      5,
    sickLeaveEN:       "5 paid sick days per year (BC ESA s. 49.1, effective January 1, 2022); additional unpaid illness or injury leave available.",
    sickLeaveFR:       "5 jours de congé de maladie payés par année (ESA C.-B. art. 49.1, en vigueur depuis le 1er janvier 2022); des congés supplémentaires non payés pour maladie ou blessure sont également disponibles.",
    groupTermStatEN:   "BC ESA s. 64 (50+ employees in 2 months); written notice to Director of Employment Standards required",
    groupTermStatFR:   "ESA C.-B. art. 64 (50 employés ou plus dans 2 mois); avis écrit au Directeur des normes d'emploi requis",
    groupThreshold50:  8,
    groupThreshold200: 12,
    groupThreshold500: 16,
    groupTrigger:      "50 or more employees terminated in a 2-month period",
    groupTriggerFR:    "50 employés ou plus mis à pied dans une période de 2 mois",
    rightToDisconnect: false,
    rtdStatEN:         null,
    rtdStatFR:         null,
    electronicMon:     false,
    emStatEN:          null,
    emStatFR:          null,
    nonCompeteBan:     false,
    ncStatEN:          "Common law — Shafron v. KRG Insurance Brokers (Western) Inc., 2009 SCC 6 applies: the court will not blue-pencil (rewrite) an overbroad restrictive covenant; it is void in its entirety",
    ncStatFR:          "Common law — Shafron c. KRG Insurance Brokers (Western) Inc., 2009 CSC 6 : le tribunal ne modifiera pas (blue-pencilling) une clause restrictive excessive; elle est nulle dans son intégralité",
    harassStatEN:      "Workers Compensation Act, R.S.B.C. 2019, c. 1, Part 3; WorkSafeBC OHS Regulation Part 4.27 — workplace bullying and harassment",
    harassStatFR:      "Workers Compensation Act, R.S.B.C. 2019, ch. 1, Partie 3; Règlement OHS de WorkSafeBC, Partie 4.27 — intimidation et harcèlement au travail",
    harassBodyEN:      "WorkSafeBC / BC Human Rights Tribunal",
    harassBodyFR:      "WorkSafeBC / Tribunal des droits de la personne de la C.-B.",
    harassFineEN:      "WorkSafeBC administrative penalties; BC Human Rights Tribunal may award unlimited compensation",
    harassFineFR:      "Sanctions administratives de WorkSafeBC; le Tribunal des droits de la personne de la C.-B. peut accorder des dommages-intérêts illimités",
    privacyStatEN:     "Personal Information Protection Act (PIPA), S.B.C. 2003, c. 63 — BC is a 'substantially similar' province; PIPA applies instead of PIPEDA for provincially regulated employers",
    privacyStatFR:     "Personal Information Protection Act (PIPA), S.B.C. 2003, ch. 63 — la C.-B. est une province « essentiellement similaire »; la PIPA s'applique à la place de la LPRPDE pour les employeurs de compétence provinciale",
    hrStatEN:          "Human Rights Code, R.S.B.C. 1996, c. 210",
    hrStatFR:          "Human Rights Code, R.S.B.C. 1996, ch. 210",
    payEquityEN:       "No mandatory pay equity legislation in BC as of 2026 — voluntary guidance only; federal Pay Equity Act applies to federally regulated employers only",
    payEquityFR:       "Aucune législation obligatoire sur l'équité salariale en C.-B. à ce jour — orientation volontaire seulement; la Loi sur l'équité salariale fédérale ne s'applique qu'aux employeurs de compétence fédérale",
    govLawEN:          "Province of British Columbia",
    govLawFR:          "province de la Colombie-Britannique",
    unjustDismissEN:   "BC ESA — complaint to Employment Standards Branch; common law wrongful dismissal action in BC Supreme Court",
    unjustDismissFR:   "ESA C.-B. — plainte à la Direction des normes d'emploi; action en common law devant la Cour suprême de la C.-B.",
    parentalStatEN:    "BC ESA ss. 50–54 (maternity leave: 17 weeks; parental leave: 62 weeks) + federal EI parental benefits",
    parentalStatFR:    "ESA C.-B. arts. 50–54 (congé de maternité : 17 semaines; congé parental : 62 semaines) + prestations parentales de l'AE fédérale",
    roeStatEN:         "Service Canada ROE Web — Code E (dismissal); Code N (resignation)",
    roeStatFR:         "ROE Web de Service Canada — Code E (congédiement); Code N (démission)",
    waksdaleApplies:   true,
    waksdaleNoteEN:    "Waksdale v. Swegon North America Inc., 2020 ONCA 391 is binding in Ontario. BC courts have not yet definitively adopted the same approach, but the principle that an illegal termination clause renders the entire section unenforceable is consistent with BC common law. Counsel should ensure for-cause clauses do not derogate below BC ESA minimums.",
    waksdaleNoteFR:    "L'arrêt Waksdale c. Swegon North America Inc., 2020 ONCA 391 lie les tribunaux ontariens. Les tribunaux de C.-B. n'ont pas encore adopté définitivement la même approche, mais le principe selon lequel une clause de cessation illégale rend toute la section inapplicable est compatible avec la common law de la C.-B. S'assurer que les clauses pour motif valable ne dérogent pas aux minimums de l'ESA C.-B.",
    dufaultNoteEN:     "Dufault, 2024 ONSC 1029 is an Ontario decision. In BC, equivalent scrutiny is applied to termination clauses — any clause that excludes or limits statutory rights under the BC ESA is void (BC ESA s. 4).",
    dufaultNoteFR:     "La décision Dufault 2024 ONSC 1029 est ontarienne. En C.-B., un niveau de contrôle équivalent s'applique aux clauses de cessation — toute clause qui exclut ou limite les droits légaux prévus par l'ESA C.-B. est nulle (art. 4).",
    isCivilLaw:        false,
  },

  // ══════════════════════════════════════════════════════════════════════════
  // ALBERTA
  // ══════════════════════════════════════════════════════════════════════════
  AB: {
    code: "AB",
    nameEN: "Alberta",
    nameFR: "Alberta",
    statuteEN:         "Employment Standards Code",
    statuteFR:         "Employment Standards Code (Alberta)",
    statuteCiteEN:     "R.S.A. 2000, c. E-9",
    statuteCiteFR:     "R.S.A. 2000, ch. E-9",
    shortEN:           "AB ESC",
    shortFR:           "ESC Alb.",
    termStatEN:        "AB ESC ss. 56–68",
    termStatFR:        "ESC Alb. arts. 56–68",
    noticeFormulaEN:   "1 week per year of service (min 1 week; max 8 weeks) — AB ESC s. 57",
    noticeFormulaFR:   "1 semaine par année de service (min 1 semaine; max 8 semaines) — ESC Alb. art. 57",
    probationMonths:   3,
    hasSeverance:      false,
    severanceStat:     "AB ESC — no statutory severance separate from notice",
    severanceFormEN:   "No statutory severance pay in Alberta — employers must provide notice or pay in lieu under AB ESC s. 57 only. Common law reasonable notice may exceed statutory minimums.",
    severanceFormFR:   "Aucune indemnité de départ légale en Alberta — les employeurs doivent accorder un préavis ou une indemnité en tenant lieu en vertu de l'ESC Alb. art. 57 seulement. Le préavis raisonnable en common law peut dépasser les minimums légaux.",
    finalPayStat:      "AB ESC s. 12",
    finalPayEN:        "within 3 business days of termination (AB ESC s. 12(3)(a)); 10 days if employee resigns",
    finalPayFR:        "dans les 3 jours ouvrables suivant la cessation d'emploi (ESC Alb. art. 12(3)(a)); 10 jours si l'employé démissionne",
    vacMinWeeks:       2,
    vacMinPct:         "4%",
    vacEnhancedEN:     "3 weeks / 6% after 5 years of service (AB ESC s. 35)",
    vacEnhancedFR:     "3 semaines / 6 % après 5 ans de service (ESC Alb. art. 35)",
    vacStatEN:         "AB ESC ss. 29–43",
    vacStatFR:         "ESC Alb. arts. 29–43",
    overtimeHours:     44,
    overtimeNoteEN:    "Overtime is payable at 1.5× for hours worked beyond 44 per week (AB ESC s. 21). Alberta allows overtime banks (time off in lieu) with written agreement (AB ESC s. 22).",
    overtimeNoteFR:    "Les heures supplémentaires sont payées à 1,5 fois le taux ordinaire au-delà de 44 heures par semaine (ESC Alb. art. 21). L'Alberta permet les banques d'heures supplémentaires (congés compensatoires) sur accord écrit (ESC Alb. art. 22).",
    paidSickDays:      0,
    sickLeaveEN:       "No statutory paid sick days in Alberta — unpaid personal and family illness leave available (AB ESC Part 2, Division 7). Employer-provided sick leave in the employment contract governs.",
    sickLeaveFR:       "Aucun jour de congé de maladie payé par la loi en Alberta — des congés non payés pour maladie personnelle et familiale sont disponibles (ESC Alb. Partie 2, Division 7). Les congés de maladie prévus dans le contrat de travail s'appliquent.",
    groupTermStatEN:   "AB ESC s. 137 (50+ employees in 4 weeks); written notice to Director of Employment Standards required",
    groupTermStatFR:   "ESC Alb. art. 137 (50 employés ou plus dans 4 semaines); avis écrit au Directeur des normes d'emploi requis",
    groupThreshold50:  8,
    groupThreshold200: 12,
    groupThreshold500: 16,
    groupTrigger:      "50 or more employees terminated in a 4-week period",
    groupTriggerFR:    "50 employés ou plus mis à pied dans une période de 4 semaines",
    rightToDisconnect: false,
    rtdStatEN:         null,
    rtdStatFR:         null,
    electronicMon:     false,
    emStatEN:          null,
    emStatFR:          null,
    nonCompeteBan:     false,
    ncStatEN:          "Common law — Elsley v. J.G. Collins Insurance Agencies Ltd., [1978] 2 SCR 916 (Supreme Court affirms enforceability if reasonable); Shafron v. KRG, 2009 SCC 6 (no blue-pencilling). Alberta courts apply the same reasonableness test.",
    ncStatFR:          "Common law — Elsley c. J.G. Collins Insurance Agencies Ltd., [1978] 2 RCS 916 (la Cour suprême confirme l'applicabilité si la clause est raisonnable); Shafron c. KRG, 2009 CSC 6 (pas de blue-pencilling). Les tribunaux albertains appliquent le même critère de raisonnabilité.",
    harassStatEN:      "Occupational Health and Safety Act, R.S.A. 2000, c. O-2 (as amended 2018) — employers must investigate harassment complaints and take corrective action",
    harassStatFR:      "Occupational Health and Safety Act, R.S.A. 2000, ch. O-2 (telle que modifiée en 2018) — les employeurs doivent enquêter sur les plaintes de harcèlement et prendre des mesures correctives",
    harassBodyEN:      "Alberta Occupational Health and Safety (OHS) / Alberta Human Rights Commission",
    harassBodyFR:      "Santé et sécurité au travail de l'Alberta (OHS) / Commission des droits de la personne de l'Alberta",
    harassFineEN:      "AB OHS — up to $500,000 (individual) or $1,500,000 (corporation) per offence",
    harassFineFR:      "OHS Alb. — jusqu'à 500 000 $ (particulier) ou 1 500 000 $ (société) par infraction",
    privacyStatEN:     "Personal Information Protection Act (PIPA), S.A. 2003, c. P-6.5 — Alberta is a 'substantially similar' province; PIPA applies to provincially regulated employers",
    privacyStatFR:     "Personal Information Protection Act (PIPA), S.A. 2003, ch. P-6.5 — l'Alberta est une province « essentiellement similaire »; la PIPA s'applique aux employeurs de compétence provinciale",
    hrStatEN:          "Alberta Human Rights Act, R.S.A. 2000, c. A-25.5",
    hrStatFR:          "Alberta Human Rights Act, R.S.A. 2000, ch. A-25.5",
    payEquityEN:       "No mandatory pay equity legislation in Alberta as of 2026 — voluntary only; employers should conduct internal audits to manage liability under the Alberta Human Rights Act (wage discrimination).",
    payEquityFR:       "Aucune législation obligatoire sur l'équité salariale en Alberta à ce jour — volontaire seulement; les employeurs devraient procéder à des audits internes pour gérer les risques en vertu de l'Alberta Human Rights Act (discrimination salariale).",
    govLawEN:          "Province of Alberta",
    govLawFR:          "province de l'Alberta",
    unjustDismissEN:   "AB ESC — complaint to Director of Employment Standards; common law wrongful dismissal action in Alberta Court of King's Bench",
    unjustDismissFR:   "ESC Alb. — plainte au Directeur des normes d'emploi; action en common law devant la Cour du Roi de l'Alberta",
    parentalStatEN:    "AB ESC ss. 45.2–48 (maternity leave: 16 weeks; parental leave: 62 weeks) + federal EI parental benefits",
    parentalStatFR:    "ESC Alb. arts. 45.2–48 (congé de maternité : 16 semaines; congé parental : 62 semaines) + prestations parentales de l'AE fédérale",
    roeStatEN:         "Service Canada ROE Web — Code E (dismissal); Code N (resignation)",
    roeStatFR:         "ROE Web de Service Canada — Code E (congédiement); Code N (démission)",
    waksdaleApplies:   true,
    waksdaleNoteEN:    "Waksdale v. Swegon North America Inc., 2020 ONCA 391 is an Ontario Court of Appeal decision. Alberta courts have not been bound to follow it, but have applied similar logic — termination clauses that derogate from AB ESC minimums are unenforceable (AB ESC s. 4). Best practice: mirror Waksdale compliance in all Alberta agreements.",
    waksdaleNoteFR:    "L'arrêt Waksdale c. Swegon North America Inc., 2020 ONCA 391 émane de la Cour d'appel de l'Ontario. Les tribunaux albertains ne sont pas tenus de le suivre, mais ont appliqué un raisonnement similaire — les clauses de cessation dérogeant aux minimums de l'ESC Alb. sont inapplicables (art. 4). Bonne pratique : appliquer les normes Waksdale dans tous les contrats albertains.",
    dufaultNoteEN:     "Dufault, 2024 ONSC 1029 is Ontario-specific. In Alberta, any contractual clause that purports to limit or exclude rights under the ESC is void (AB ESC s. 4). The same drafting discipline applies.",
    dufaultNoteFR:     "La décision Dufault 2024 ONSC 1029 est propre à l'Ontario. En Alberta, toute clause contractuelle visant à limiter ou exclure des droits prévus par l'ESC Alb. est nulle (art. 4). La même rigueur rédactionnelle s'applique.",
    isCivilLaw:        false,
  },

  // ══════════════════════════════════════════════════════════════════════════
  // FEDERAL (Canada Labour Code)
  // ══════════════════════════════════════════════════════════════════════════
  FED: {
    code: "FED",
    nameEN: "Federal (Canada Labour Code)",
    nameFR: "Fédéral (Code canadien du travail)",
    statuteEN:         "Canada Labour Code",
    statuteFR:         "Code canadien du travail",
    statuteCiteEN:     "R.S.C. 1985, c. L-2",
    statuteCiteFR:     "L.R.C. 1985, ch. L-2",
    shortEN:           "CLC",
    shortFR:           "CCT",
    termStatEN:        "CLC ss. 230–232",
    termStatFR:        "CCT arts. 230–232",
    noticeFormulaEN:   "2 weeks after 3 months of service (CLC s. 230); common law notice applies for longer-service employees",
    noticeFormulaFR:   "2 semaines après 3 mois de service (CCT art. 230); le préavis raisonnable en common law s'applique aux employés de longue date",
    probationMonths:   3,
    hasSeverance:      true,
    severanceStat:     "CLC s. 235",
    severanceFormEN:   "2 days per completed year of service, minimum 5 days — available after 12 months continuous employment (CLC s. 235)",
    severanceFormFR:   "2 jours par année de service accomplie, minimum 5 jours — disponible après 12 mois d'emploi continu (CCT art. 235)",
    finalPayStat:      "CLC s. 243",
    finalPayEN:        "within 30 days of termination for most entitlements (CLC s. 243); vacation pay within 30 days",
    finalPayFR:        "dans les 30 jours suivant la cessation d'emploi pour la plupart des droits (CCT art. 243); indemnité de vacances dans les 30 jours",
    vacMinWeeks:       2,
    vacMinPct:         "4%",
    vacEnhancedEN:     "3 weeks / 6% after 5 years; 4 weeks / 8% after 10 years (CLC s. 184)",
    vacEnhancedFR:     "3 semaines / 6 % après 5 ans; 4 semaines / 8 % après 10 ans (CCT art. 184)",
    vacStatEN:         "CLC ss. 183–196",
    vacStatFR:         "CCT arts. 183–196",
    overtimeHours:     40,
    overtimeNoteEN:    "Overtime is payable at 1.5× for hours worked beyond 40 per week (CLC s. 174); sector-specific modified work arrangements exist under CLC Part III Divisions IV–V.",
    overtimeNoteFR:    "Les heures supplémentaires sont payées à 1,5 fois le taux ordinaire au-delà de 40 heures par semaine (CCT art. 174); des régimes de travail modifié propres à certains secteurs existent en vertu des Divisions IV–V de la Partie III du CCT.",
    paidSickDays:      10,
    sickLeaveEN:       "10 paid sick days per year (CLC s. 206.6, effective January 1, 2023); accessible after 3 months employment; doctor's note restrictions apply.",
    sickLeaveFR:       "10 jours de congé de maladie payés par année (CCT art. 206.6, en vigueur depuis le 1er janvier 2023); accessible après 3 mois d'emploi; des restrictions s'appliquent quant aux billets médicaux.",
    groupTermStatEN:   "CLC ss. 212–214 — 50+ employees terminated in 4 weeks; 16 weeks' notice to Minister of Labour; joint planning committee mandatory",
    groupTermStatFR:   "CCT arts. 212–214 — 50 employés ou plus mis à pied dans 4 semaines; avis de 16 semaines au ministre du Travail; comité de planification conjoint obligatoire",
    groupThreshold50:  16,   // flat 16 weeks to Minister
    groupThreshold200: 16,
    groupThreshold500: 16,
    groupTrigger:      "50 or more employees terminated in a 4-week period",
    groupTriggerFR:    "50 employés ou plus mis à pied dans une période de 4 semaines",
    rightToDisconnect: false,
    rtdStatEN:         "No statutory right-to-disconnect obligation under the CLC as of 2026 — follow employer's internal policy",
    rtdStatFR:         "Aucune obligation légale de déconnexion en vertu du CCT à ce jour — se conformer à la politique interne de l'employeur",
    electronicMon:     false,
    emStatEN:          null,
    emStatFR:          null,
    nonCompeteBan:     false,
    ncStatEN:          "Common law — Shafron v. KRG, 2009 SCC 6; Elsley v. J.G. Collins, [1978] 2 SCR 916. No statutory ban for federally regulated employers.",
    ncStatFR:          "Common law — Shafron c. KRG, 2009 CSC 6; Elsley c. J.G. Collins, [1978] 2 RCS 916. Aucune interdiction légale pour les employeurs de compétence fédérale.",
    harassStatEN:      "Canada Labour Code, Part II (Occupational Health and Safety); Workplace Harassment and Violence Prevention Regulations (WPHVPR), SOR/2020-130 — annual report to Employment and Social Development Canada required",
    harassStatFR:      "Code canadien du travail, Partie II (Santé et sécurité au travail); Règlement sur la prévention du harcèlement et de la violence dans le lieu de travail (RPHVLT), DORS/2020-130 — rapport annuel à Emploi et Développement social Canada requis",
    harassBodyEN:      "Employment and Social Development Canada (ESDC) — Labour Program",
    harassBodyFR:      "Emploi et Développement social Canada (EDSC) — Programme du travail",
    harassFineEN:      "CLC Part II — up to $1,000,000 per offence (corporation); officer liability",
    harassFineFR:      "CCT Partie II — jusqu'à 1 000 000 $ par infraction (société); responsabilité des dirigeants",
    privacyStatEN:     "Personal Information Protection and Electronic Documents Act (PIPEDA), S.C. 2000, c. 5 — applies to all federally regulated employers; breach notification to Privacy Commissioner required",
    privacyStatFR:     "Loi sur la protection des renseignements personnels et les documents électroniques (LPRPDE), L.C. 2000, ch. 5 — s'applique à tous les employeurs de compétence fédérale; notification des atteintes au Commissaire à la protection de la vie privée requise",
    hrStatEN:          "Canadian Human Rights Act, R.S.C. 1985, c. H-6",
    hrStatFR:          "Loi canadienne sur les droits de la personne, L.R.C. 1985, ch. H-6",
    payEquityEN:       "Pay Equity Act (federal), S.C. 2018, c. 27, s. 416 — mandatory for federally regulated employers with 10+ employees; proactive pay equity plan required; Canadian Human Rights Commission enforces",
    payEquityFR:       "Loi sur l'équité salariale (fédérale), L.C. 2018, ch. 27, art. 416 — obligatoire pour les employeurs de compétence fédérale de 10 salariés ou plus; un plan d'équité salariale proactif est requis; la Commission canadienne des droits de la personne applique la loi",
    govLawEN:          "Federal law (Canada Labour Code)",
    govLawFR:          "droit fédéral (Code canadien du travail)",
    unjustDismissEN:   "CLC s. 240 (unjust dismissal complaint — available to non-managerial employees with 12+ months service; reinstatement is a remedy); common law wrongful dismissal in Federal Court or superior court",
    unjustDismissFR:   "CCT art. 240 (plainte en congédiement injuste — disponible aux employés non cadres avec 12 mois ou plus de service; la réintégration est un recours disponible); action en droit commun devant la Cour fédérale ou une cour supérieure",
    parentalStatEN:    "CLC Part III, Div. VII (maternity leave: 17 weeks; parental leave: up to 63 weeks) + federal EI standard or extended parental benefits",
    parentalStatFR:    "CCT Partie III, Div. VII (congé de maternité : 17 semaines; congé parental : jusqu'à 63 semaines) + prestations parentales standard ou prolongées de l'AE fédérale",
    roeStatEN:         "Service Canada ROE Web — Code E (dismissal); Code N (resignation); Code D (illness/injury for sick days); ESDC administers",
    roeStatFR:         "ROE Web de Service Canada — Code E (congédiement); Code N (démission); Code D (maladie/blessure pour jours de congé); administré par EDSC",
    waksdaleApplies:   true,
    waksdaleNoteEN:    "Waksdale v. Swegon North America Inc., 2020 ONCA 391 is an Ontario decision. Federally regulated employers are governed by the CLC, not provincial ESA. However, analogous principles apply: CLC s. 167(1) prohibits contracting out of CLC rights. A termination clause that purports to limit entitlements below CLC minimums (notice + severance) is void. Additionally, CLC-covered employees with 12+ months of service have an unjust dismissal remedy (CLC s. 240) that is separate from common law.",
    waksdaleNoteFR:    "L'arrêt Waksdale c. Swegon North America Inc., 2020 ONCA 391 émane de l'Ontario. Les employeurs de compétence fédérale sont régis par le CCT, non par les lois provinciales. Toutefois, des principes analogues s'appliquent : l'art. 167(1) du CCT interdit de déroger aux droits prévus par le CCT. Une clause de cessation visant à limiter les droits en deçà des minimums du CCT (préavis + indemnité de départ) est nulle. De plus, les employés couverts par le CCT ayant 12 mois ou plus de service disposent d'un recours en congédiement injuste (CCT art. 240) distinct de la common law.",
    dufaultNoteEN:     "Dufault, 2024 ONSC 1029 is Ontario-specific. Under the CLC, CLC s. 167(1) has the same prohibitory effect — any attempt to contract out of CLC entitlements is void. For CLC employers, special attention should be paid to the unjust dismissal provisions (CLC s. 240) which cannot be excluded by contract.",
    dufaultNoteFR:     "La décision Dufault 2024 ONSC 1029 est propre à l'Ontario. En vertu du CCT, l'art. 167(1) du CCT a le même effet prohibitif — toute tentative de déroger aux droits prévus par le CCT est nulle. Pour les employeurs assujettis au CCT, une attention particulière doit être portée aux dispositions sur le congédiement injuste (art. 240 du CCT) qui ne peuvent être exclues par contrat.",
    isCivilLaw:        false,
    // Federal-only
    unjustDismissRightEN: "CLC s. 240 — non-managerial employees with 12+ months service may file an unjust dismissal complaint; reinstatement is available as a remedy (unlike Ontario ESA which does not provide reinstatement)",
    unjustDismissRightFR: "CCT art. 240 — les employés non cadres avec 12 mois ou plus de service peuvent déposer une plainte en congédiement injuste; la réintégration est disponible comme recours (contrairement à la LNE de l'Ontario qui ne prévoit pas la réintégration)",
  },
};

module.exports = JURISDICTIONS;
